# Generated by Django 6.0.3 on 2026-06-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
    ]
