# Generated by Django 6.0.3 on 2026-06-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('face_scan', 'Face Scan')], default='manual', max_length=20),
        ),
    ]
